version: '3'
services:
  jenkins:
    container_name: jenkins
    image: gcr.io/prueba-ir-devops/jenkins:1.0.0
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - $PWD/credentials:/var/credentials
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  
networks:
  net: